# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_to_text_pb2 as audio__to__text__pb2


class RecognizeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recognize_audio = channel.stream_stream(
                '/recognize.Recognize/recognize_audio',
                request_serializer=audio__to__text__pb2.Message.SerializeToString,
                response_deserializer=audio__to__text__pb2.Response.FromString,
                )
        self.disconnect = channel.unary_unary(
                '/recognize.Recognize/disconnect',
                request_serializer=audio__to__text__pb2.Info.SerializeToString,
                response_deserializer=audio__to__text__pb2.EventResponse.FromString,
                )
        self.start = channel.unary_unary(
                '/recognize.Recognize/start',
                request_serializer=audio__to__text__pb2.Info.SerializeToString,
                response_deserializer=audio__to__text__pb2.EventResponse.FromString,
                )
        self.end = channel.unary_unary(
                '/recognize.Recognize/end',
                request_serializer=audio__to__text__pb2.Info.SerializeToString,
                response_deserializer=audio__to__text__pb2.EventResponse.FromString,
                )
        self.language_reset = channel.unary_unary(
                '/recognize.Recognize/language_reset',
                request_serializer=audio__to__text__pb2.Info.SerializeToString,
                response_deserializer=audio__to__text__pb2.EventResponse.FromString,
                )


class RecognizeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def recognize_audio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def end(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def language_reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognizeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recognize_audio': grpc.stream_stream_rpc_method_handler(
                    servicer.recognize_audio,
                    request_deserializer=audio__to__text__pb2.Message.FromString,
                    response_serializer=audio__to__text__pb2.Response.SerializeToString,
            ),
            'disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.disconnect,
                    request_deserializer=audio__to__text__pb2.Info.FromString,
                    response_serializer=audio__to__text__pb2.EventResponse.SerializeToString,
            ),
            'start': grpc.unary_unary_rpc_method_handler(
                    servicer.start,
                    request_deserializer=audio__to__text__pb2.Info.FromString,
                    response_serializer=audio__to__text__pb2.EventResponse.SerializeToString,
            ),
            'end': grpc.unary_unary_rpc_method_handler(
                    servicer.end,
                    request_deserializer=audio__to__text__pb2.Info.FromString,
                    response_serializer=audio__to__text__pb2.EventResponse.SerializeToString,
            ),
            'language_reset': grpc.unary_unary_rpc_method_handler(
                    servicer.language_reset,
                    request_deserializer=audio__to__text__pb2.Info.FromString,
                    response_serializer=audio__to__text__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recognize.Recognize', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recognize(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def recognize_audio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/recognize.Recognize/recognize_audio',
            audio__to__text__pb2.Message.SerializeToString,
            audio__to__text__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recognize.Recognize/disconnect',
            audio__to__text__pb2.Info.SerializeToString,
            audio__to__text__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recognize.Recognize/start',
            audio__to__text__pb2.Info.SerializeToString,
            audio__to__text__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def end(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recognize.Recognize/end',
            audio__to__text__pb2.Info.SerializeToString,
            audio__to__text__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def language_reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recognize.Recognize/language_reset',
            audio__to__text__pb2.Info.SerializeToString,
            audio__to__text__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
